### PR TITLE
Wait for processes to terminate before exiting

### PR DESCRIPTION
**Pull request by ghost**
As far as I can tell from re-reading the code, the os.Exit() isn't actually necessary; when all the processes stop the loop at the bottom will finish and the main function will return, ending the entire program.

### CODE REVIEW

**Comment by rwestlund** [comment]
I'm pretty sure you've made it so that SIGTERM will restart it's children, rather that exit anything.  Remember that handleDone() can restart a process that exits, depending on the config.  Once you have awningtracker shutting down cleanly, use it to test your changes here, then I'll merge after testing.

**Comment by ghost** [comment]
Ah, I missed that :( Still, handleDone only restarts processes that fail, right? And they shouldn't if sent SIGTERM...

Though apparently in the jail paladin exits even if awningtracker is SIGKILLed. This may be an unrelated bug: paladin doesn't seem to restart anything no matter what. I even got the log to show "Process awningtracker failed after 9 seconds" but there's no evidence of any attempt to restart it. Paladin just exits, even after my changes.

Wait a minute. handleRunning and handleDone are passed the runningProcesses counter by value. That might be why nothing is restarting. The main routine's final loop tells it to restart, and it does start launchProcess again, but the runningProcesses value that the main thread holds isn't getting un-decremented, so the main loop still exits as soon as the main goroutine is back on it. I don't think that can be the entire problem, since the connections still persist if Awningtracker is directly sent TERM and paladin doesn't report any error, but it still seems like its own issue. I think the only reason it's not causing a problem that handleRunning can't increment the counter is because main() does it when it launches them. To confirm my theory, I removed the line where handleRunning increments runningProcesses and rebuilt and copied it into the jail, and it seems to work exactly the same.

**Comment by rwestlund** [comment]
Processes may react differently to SIGTERM.  If handled, it should be a graceful shutdown.  If not handled, it's not graceful; think about what happens in python when you send SIGINT (^C).

Nice catch; it is indeed passing an int by value.  I think we had in it a global struct originally, then introduced this bug when making it local to main().

I want you to review the paladin code in detail and fix any bugs you find.  You have a lot more expertise now than you did the last time you worked on this, so you may see other issues that one of us introduced.

**Comment by ghost** [comment]
Okay, new commit. I've tested this with a lot of cases:

- SIGTERM awningtracker: paladin exits
- SIGKILL awningtracker: paladin restarts it
- SIGTERM paladin: paladin exits, taking awningtracker with it
- SIGKILL paladin: paladin dies, awningtracker left alive (I assume this is because we change the PGID)

I ended up moving the signal handling goroutine into the same loop as the other stuff. It seemed like the other way was to add a channel for that routine to signal the mainloop when a SIGTERM is received and it should stop trying to restart things, but that sounded ugly.

**Pull request merged**
